{{- if eq .Values.ingress.type "microgateway" -}}
{{-   $app := "transactionApproval" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
{{-   $app_values := get .Values.iam.apps $app -}}
{{-   $suffix := $app_values.dedicatedDeployment.suffix | default (include "airlock-iam.mapAppName" $app) -}}
{{-   $moduleName := print $fullName "-" $suffix | lower -}}
{{-   $moduleType := include "airlock-iam.mapAppName" $app -}}
{{-   $path := include "airlock-iam.modulePath" (dict "app" $app "app_values" $app_values "instanceName" $.Values.iam.instanceName) -}}
{{-   if $app_values.enable }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: DenyRules
metadata:
  name: {{ $moduleName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $moduleType }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
spec:
  request:
    builtIn:
      settings:
        level: Strict
        threatHandlingMode: Block
      overrides:
        - conditions:
            ruleKeys:
              - SSRF
            types:
              - JSON
          settings:
            level: Unfiltered
      exceptions:
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            jsonPath: "$.username"
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.id"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.clientDataJSON"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.userHandle"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.signature"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "SQL"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.authenticatorData"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            name:
              matcher:
                regex: "^filter$"
                ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.id"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.clientDataJSON"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.userHandle"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.signature"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.authenticatorData"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.id"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.clientDataJSON"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.userHandle"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.signature"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
      - ruleKeys:
        - "IDOR"
        blockedData:
          json:
            value:
              matcher:
                regex: "^[a-zA-Z0-9_\\-]*$"
                ignoreCase: false
            jsonPath: "$.publicKeyCredential.response.authenticatorData"
        requestConditions:
          method:
          - "POST"
          path:
            matcher:
              regex: "^{{ $path }}/rest/transaction-approval/fido/assertion-response/check/?$"
              ignoreCase: false
{{-   end }}
{{- end }}
