{{- if eq .Values.ingress.type "microgateway" -}}
{{-   $app := "serviceContainer" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
{{-   $app_values := get .Values.iam.apps $app -}}
{{-   $suffix := $app_values.dedicatedDeployment.suffix | default (include "airlock-iam.mapAppName" $app) -}}
{{-   $moduleName := print $fullName "-" $suffix | lower -}}
{{-   $moduleType := include "airlock-iam.mapAppName" $app -}}
{{-   if $app_values.enable }}
apiVersion: microgateway.airlock.com/v1alpha1
kind: DenyRules
metadata:
  name: {{ $moduleName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $moduleType }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
spec:
  request:
    builtIn:
      settings:
        level: Strict
        threatHandlingMode: Block
# SSRF deny rule introduced in Microgateway 4.4
      {{- if semverCompare ">=4.4" .Values.ingress.microgateway.version }}
      overrides:
        - conditions:
            ruleKeys:
              - SSRF
            types:
              - JSON
          settings:
            level: Unfiltered
      {{- end }}
      exceptions:
      - ruleKeys:
        - "SQL"
        blockedData:
          parameter:
            source: Any
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          invert: false
          path:
            matcher:
              regex: "^{{ $app_values.path }}/serviceContainer$"
              ignoreCase: false
      - ruleKeys:
        - "XSS"
        blockedData:
          parameter:
            source: Any
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          invert: false
          path:
            matcher:
              regex: "^{{ $app_values.path }}/serviceContainer$"
              ignoreCase: false
      - ruleKeys:
        - "HPP"
        blockedData:
          parameter:
            source: Any
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          invert: false
          path:
            matcher:
              regex: "^{{ $app_values.path }}/serviceContainer$"
              ignoreCase: false
      {{- if semverCompare ">=4.4" .Values.ingress.microgateway.version }}
      - ruleKeys:
        - "SSRF"
        blockedData:
          parameter:
            source: Any
            name:
              matcher:
                regex: "^v-loc$"
                ignoreCase: false
        requestConditions:
          invert: false
          path:
            matcher:
              regex: "^{{ $app_values.path }}/serviceContainer$"
              ignoreCase: false
      {{- end }}
{{-   end }}
{{- end }}
