{{/*
{{- if eq .Values.ingress.type "microgateway" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
apiVersion: microgateway.airlock.com/v1alpha1
kind: DenyRules
metadata:
  name: {{ $fullName }}-unspecified-path
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $moduleType }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
spec:
  request:
    builtIn:
      settings:
        level: Strict
        threatHandlingMode: Block
    custom:
      rules:
        - blockData:
            path:
              matcher:
                regex: ".*"
          ruleKey: "BLOCK_UNSPECIFIED_PATH"
{{- end }}
*/}}
