{{- if eq .Values.ingress.type "microgateway" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
{{-   range $app, $app_values := .Values.iam.apps -}}
{{-     if $app_values.enable }}
{{-       $suffix := $app_values.dedicatedDeployment.suffix | default (include "airlock-iam.mapAppName" $app) -}}
{{-       $moduleName := print $fullName "-" $suffix | lower -}}
{{-       $moduleType := include "airlock-iam.mapAppName" $app -}}
{{-       if ne $app "loginapp" -}}
---
apiVersion: microgateway.airlock.com/v1alpha1
kind: OpenAPI
metadata:
  name: {{ $moduleName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $moduleType }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
spec:
  settings:
    schema:
      source:
        configMapRef:
          name: {{ $moduleName }}-openapi
    threatHandlingMode: Block

{{-       else }}
{{-         range list "public" "protected" "oauth2" }}
---
apiVersion: microgateway.airlock.com/v1alpha1
kind: OpenAPI
metadata:
  name: {{ $moduleName }}-{{ . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $moduleType }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
spec:
  settings:
    schema:
      source:
        configMapRef:
          name: {{ $moduleName }}-openapi-{{ . }}
    threatHandlingMode: Block
{{-         end }}
{{-       end }}
{{-     end }}
{{-   end }}
{{- end }}
