{{- if eq .Values.ingress.type "microgateway" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
apiVersion: microgateway.airlock.com/v1alpha1
kind: Parser
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
spec:
  request:
    defaultContentType: "application/json"
{{- end }}
