{{- if eq .Values.ingress.type "microgateway" -}}
{{-   if semverCompare ">=5.1" .Values.ingress.microgateway.version }}
{{-     $fullName := include "airlock-iam.fullname" . -}}
apiVersion: microgateway.airlock.com/v1alpha1
kind: Telemetry
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
spec:
  correlation:
    idSource:
      header:
        name: "X-Correlation-Id"
{{-   end }}
{{- end }}
