{{- $databaseDeployment := include "airlock-iam.deploymentType" . -}}
{{- if and (ne $databaseDeployment "none") (ne $databaseDeployment "") }}
{{- $fullName := include "airlock-iam.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-init
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "include/init_db" "include/init_instance" "include/init_config" }}
  {{ regexSplit "/" . -1 | last }}: |-
    {{- $files.Get . | nindent 4 }} 
  {{- end }}
{{- end }}
