{{- $the_name := include "airlock-iam.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $the_name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range tuple "scripts/init_db" }}
  {{ regexSplit "/" . -1 | last }}: |-
    {{- $files.Get . | nindent 4 }} 
  {{- end }}
