{{- $fullName := include "airlock-iam.fullname" . -}}
{{- $the_name := $fullName -}}
{{- $hasShared := include "airlock-iam.hasShared" . -}}
{{- $hasSandbox := include "airlock-iam.hasSandbox" . -}}
{{- if $hasShared -}}
{{-   $suffix := "" -}}
{{-   if $hasSandbox -}}
{{-     $suffix = "shared" -}}
{{-   end -}}
{{-   if $suffix -}}
{{-     $the_name = print $fullName "-" $suffix -}}
{{-   end -}}
{{-   $propIdx := include "airlock-iam.findProperties" .Values.iam.shared.propertiesName -}}
{{-   $instanceProp := index .Values.iam.instanceProperties (int $propIdx) -}}
apiVersion: v1
kind: Deployment
metadata:
  name: {{ $the_name }}
  {{- if $suffix }}
  labels:
    app.kubernetes.io/component: {{ $suffix }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  {{- if $suffix }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $the_name }}
      app.kubernetes.io/component: {{ $suffix }}
  {{- end }}
  template:
    metadata:
      {{- if $suffix }}
      labels:
        app.kubernetes.io/component: {{ $suffix }}
      {{- end }}
    spec:
      serviceAccountName: {{ $fullName }}
      automateServiceAccountToken: true
      dnsPolicy: clusterFirst
      enableServiceLinks: true
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ $the_name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ quote .Values.image.pullPolicy }}
          args: ["run", "-i", {{ quote $.Values.iam.instanceName }}]
          env:
            {{- if $.Values.iam.environmentId }}
            - name: IAM_ENVIRONMENT_ID
              value: {{ $.Values.iam.environmentId }}
            {{- end }}
            - name: IAM_CONFIG_FORMAT
              value: {{ ternary "xml" "yaml" (eq (lower $.Values.iam.configFormat) "xml") }}
            {{- if .Values.iam.apps.adminapp.path }}
            - name: IAM_ADMINAPP_URL_PATH
              value: {{ .Values.iam.apps.adminapp.path }}
            {{- end }}
            {{- if .Values.iam.apps.loginapp.path }}
            - name: IAM_LOGINAPP_URL_PATH
              value: {{ .Values.iam.apps.loginapp.path }}
            {{- end }}
            {{- if .Values.iam.apps.transactionApproval.path }}
            - name: IAM_TRANSACTION_APPROVAL_URL_PATH
              value: {{ .Values.iam.apps.transactionApproval.path }}
            {{- end }}
            {{- if .Values.iam.apps.serviceContainer.path }}
            - name: IAM_SERVICE_CONTAINER_URL_PATH
              value: {{ .Values.iam.apps.serviceContainer.path }}
            {{- end }}
            {{- if .Values.iam.apps.apiPolicyService.path }}
            - name: IAM_API_POLICY_SERVICE_URL_PATH
              value: {{ .Values.iam.apps.apiPolicyService.path }}
            {{- end }}
            - name: IAM_MODULES
              value: {{ include "airlock-iam.listModulesShared" . }}
            - name: IAM_WEB_SERVER_HTTP_PORT
              value: "8080"
            - name: IAM_WEB_SERVER_HTTPS_PORT
              value: "8443"
            {{- if eq $instanceProp.logging.level "" }}
            - name: IAM_LOG_LEVEL
              value: INFO
            {{- else if ne $instanceProp.logging.level "" }}
            - name: IAM_LOG_LEVEL
              value: {{ $instanceProp.logging.level }}
            {{- end }}
            {{- if $instanceProp.logging.local.enable }}
            {{-   if $instanceProp.logging.local.structured }}
            - name: IAM_LOG_STRUCTURED_FILE_ENABLED
              value: "true"
            - name: IAM_LOG_MAIN_ENABLED
              value: "false"
            {{-   else }}
            - name: IAM_LOG_STRUCTURED_FILE_ENABLED
              value: "false"
            - name: IAM_LOG_MAIN_ENABLED
              value: "true"
            {{-   end }}
            {{- end }}
            {{- if $instanceProp.logging.elasticsearchUrl }}
            - name: IAM_LOG_ELASTICSEARCH_URL
              value: {{ $instanceProp.logging.elasticsearchUrl }}
            {{- end }}
            {{- if $instanceProp.logging.webserver }}
            - name: IAM_WEB_SERVER_ACCESS_LOG_FILE_ENABLED
              value: "true"
            {{- end }}
            {{- if $instanceProp.metrics }}
            - name: IAM_METRICS_PORT
              value: {{ quote $instanceProp.metrics }}
            {{- end }}
            - name: IAM_HEALTH_PORT
              value: "8081"
            {{- range $name, $value := mergeOverwrite $.Values.env $instanceProp.env .Values.iam.shared.env }}
            - name: {{ quote $name }}
              value: {{ quote $value }}
            {{- end }}
            - name: TZ
              value: {{ .Values.global.timezone }}
          ports:
            - containerPort: 8080
              name: http
    {{- if .Values.resourceOptions }}
          resources:
    {{ toYaml .Values.resourceOptions | indent 8 }}
    {{- end }}
          volumeMounts:
            {{- if .Values.persistence.config.enable }}
            - mountPath: /home/airlock/instances
              name: config
            {{- end }}
            {{- if .Values.persistence.logs.enable }}
            - mountPath: {{ print "/home/airlock/instances/" .Values.iam.instanceName "/logs" }}
              name: logs
            {{- end }}
            - mountPath: /home/airlock/license.txt
              name: license
              subPath: license.txt
            - mountPath: /home/airlock/work
              name: work
      restartPolicy: {{ quote .Values.restartPolicy }}
      volumes:
        {{- if .Values.persistence.config.enable }}
        - name: config
          {{- if eq .Values.persistence.config.type "request" }}
          persistentVolumeClaim:
            claimName: {{ print $fullName "-" (ternary .Values.persistence.config.claim "config" (ne .Values.persistence.config.claim "")) }}
          {{- else if eq .Values.persistence.config.type "existing" }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.claim }}
          {{- else if eq .Values.persistence.config.type "remote" }}
          {{ .Values.persistence.config.remote.type }}:
            server: {{ .Values.persistence.config.remote.server }}
            path: {{ .Values.persistence.config.remote.path }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if .Values.persistence.logs.enable }}
        - name: logs
          {{- if eq .Values.persistence.logs.type "request" }}
          persistentVolumeClaim:
            claimName: {{ print $fullName "-" (ternary .Values.persistence.logs.claim "logs" (ne .Values.persistence.logs.claim "")) }}
          {{- else if eq .Values.persistence.logs.type "existing" }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.logs.claim }}
          {{- else if eq .Values.persistence.logs.type "remote" }}
          {{ .Values.persistence.logs.remote.type }}:
            server: {{ .Values.persistence.logs.remote.server }}
            path: {{ .Values.persistence.logs.remote.path }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - name: license
          {{- if has (lower $.Values.iam.license.type) (list "cm" "configmap") }}
          configMap:
            name: {{ $.Values.iam.license.name }}
          {{- else }}
          secret:
            secretName: {{ $.Values.iam.license.name }}
          {{- end }}
        - name: work
          emptyDir: {}
{{- end -}}
