{{- if eq .Values.ingress.type "httpproxy" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
{{-   $the_name := $fullName -}}
{{-   $hasSandbox := include "airlock-iam.hasSandbox" . -}}
{{-   $sharedDone := false -}}
{{-   $createShared := false -}}
{{-   $svc := .Values.service -}}
{{-   range $app, $app_values := .Values.iam.apps -}}
{{-     if $app_values.enable -}}
{{-       $suffix := "" -}}
{{-       if $app_values.sandbox.enable -}}
{{-         $suffix = $app_values.sandbox.suffix | default $app -}}
{{-         $the_name = print $fullName "-" $suffix -}}
{{-         $createShared = false -}}
{{-       else -}}
{{-         if eq $hasSandbox "true" -}}
{{-           $suffix = ternary $.Values.iam.shared.suffix "shared" (ne $.Values.iam.shared.suffix "") -}}
{{-         end -}}
{{-         if $suffix -}}
{{-           $the_name = print $fullName "-" $suffix -}}
{{-         end -}}
{{-         $createShared = true -}}
{{-       end -}}
{{-       if or (not $createShared) (not $sharedDone) }}
{{-         $_ := set $ "IAM_the_name" $the_name }}
{{-         $_ := set $ "IAM_suffix" $suffix }}
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $the_name }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  virtualhost:
    fqdn: {{ $.Values.ingress.dns.hostname }}
  {{- if ne $.Values.ingress.tls.secretName "" }}
  tls:
    secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  routes:
    - conditions:
      - prefix: {{ ternary "/" (print "/" $.Values.iam.instanceName "-" $app) $createShared }}
        {{- if eq $.Values.ingress.tls.secretName "" }}
      permitInsecure: true
      {{- end }}
      services:
        - name: {{ $the_name }}
          port: 80
      {{- if ne $.Values.ingress.timeout "" }}
      timeoutPolicy:
        response: {{ $.Values.ingress.timeout }}
      {{- end }}
{{-       end }}
{{-       if $createShared -}}
{{-         $sharedDone = true -}}
{{-       end }}
{{-     end }}
{{-   end }}
{{- end -}}
