{{- if or (eq .Values.ingress.type "gatewayAPI") (eq .Values.ingress.type "httproute") -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  {{- if contains "/" $.Values.ingress.gatewayAPI.gateway }}
    - name: {{ regexSplit "/" $.Values.ingress.gatewayAPI.gateway -1 | last }}
      namespace: {{ regexSplit "/" $.Values.ingress.gatewayAPI.gateway -1 | first }}
  {{- else }}
    - name: {{ $.Values.ingress.gatewayAPI.gateway }}
    {{- if ne $.Values.ingress.gatewayAPI.namespace "" }}
      namespace: {{ $.Values.ingress.gatewayAPI.namespace }}
    {{- end }}
  {{- end }}
    {{- if $.Values.ingress.gatewayAPI.sectionName }}
      sectionName: {{ $.Values.ingress.gatewayAPI.sectionName }}
    {{- end }}
    {{- if ne (int $.Values.ingress.gatewayAPI.port) 0 }}
      port: {{ $.Values.ingress.gatewayAPI.port }}
    {{- end }}
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ $.Values.ingress.dns.hostname }}
  rules:
    {{- if eq .Values.iam.appDeploymentStrategy "single" }}
    - backendRefs:
        - name: {{ $fullName }}
          port:  {{ ternary 443 80 .Values.iam.combined.backendTLS.enable }}
          weight: 1
          group: ''
          kind: Service
      matches:
        - path:
            value: "/"
            type: PathPrefix
      {{- if ne $.Values.ingress.timeout "" }}
      timeouts:
        backendRequest: {{ $.Values.ingress.timeout }}
      {{- end }}
    {{- else if eq .Values.iam.appDeploymentStrategy "multi" }}
    {{-   range $app, $app_values := .Values.iam.apps }}
    {{-     $path := include "airlock-iam.modulePath" (dict "app" $app "app_values" $app_values "instanceName" $.Values.iam.instanceName) -}}
    {{-     if $app_values.enable }}
    - backendRefs:
        - name: {{ print $fullName "-" ($app_values.dedicatedDeployment.suffix | default (include "airlock-iam.mapAppName" $app)) }}
          port: {{ ternary 443 80 $app_values.dedicatedDeployment.backendTLS.enable }}
      matches:
        - path:
            value: {{ $path }}
            type: PathPrefix
      {{- if ne $.Values.ingress.timeout "" }}
      timeouts:
        backendRequest: {{ $.Values.ingress.timeout }}
      {{- end }}
    {{-     end }}
    {{-   end }}
    {{- end }}
{{- end -}}
