{{- if eq .Values.ingress.type "httpproxy" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  virtualhost:
    fqdn: {{ $.Values.ingress.dns.hostname }}
  {{- if ne $.Values.ingress.tls.secretName "" }}
  tls:
    secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  routes:
    {{- if eq .Values.iam.appDeploymentStrategy "single" }}
    - conditions:
      - prefix: "/"
      {{- if eq $.Values.ingress.tls.secretName "" }}
      permitInsecure: true
      {{- end }}
      services:
        - name: {{ $fullName }}
          port: 80
      {{- if ne $.Values.ingress.timeout "" }}
      timeoutPolicy:
        response: {{ $.Values.ingress.timeout }}
      {{- end }}
    {{- else if eq .Values.iam.appDeploymentStrategy "multi" }}
    {{-   range $app, $app_values := .Values.iam.apps }}
    {{-     if $app_values.enable }}
    - conditions:
      - prefix: {{ print "/" ($.Values.iam.apps.adminapp.path | default (print $.Values.iam.instanceName "-" $app)) }}
      {{- if eq $.Values.ingress.tls.secretName "" }}
      permitInsecure: true
      {{- end }}
      services:
        - name: {{ print $fullName "-" ($app_values.dedicatedDeployment.suffix | default (include "airlock-iam.mapAppName" $app)) }}
          port: 80
      {{- if ne $.Values.ingress.timeout "" }}
      timeoutPolicy:
        response: {{ $.Values.ingress.timeout }}
      {{- end }}
    {{-     end }}
    {{-   end }}
    {{- end }}
{{- end -}}
