{{- if eq .Values.ingress.type "gatewayAPI" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  {{- if contains "/" $.Values.ingress.gatewayAPI.gateway }}
    - name: {{ $.Values.ingress.gatewayAPI.gateway | split "/" | index 1 }}
    - namespace: {{ $.Values.ingress.gatewayAPI.gateway | split "/" | first }}
  {{- else }}
    - name: {{ $.Values.ingress.gatewayAPI.gateway }}
    {{- if ne $.Values.ingress.gatewayAPI.namespace "" }}
    - namespace: {{ $.Values.ingress.gatewayAPI.namespace }}
    {{- end }}
  {{- end }}
  hostnames:
    - {{ $.Values.ingress.dns.hostname }}
  rules:
    {{- if eq .Values.iam.appDeploymentStrategy "single" }}
    - backendRefs:
        - name: {{ $fullName }}
          port: 80
      matches:
        - path:
            value: "/"
            type: PathPrefix
      {{- if ne $.Values.ingress.timeout "" }}
      timeouts:
        backendRequest: {{ $.Values.ingress.timeout }}
      {{- end }}
    {{- else if eq .Values.iam.appDeploymentStrategy "multi" }}
    {{-   range $app, $app_values := .Values.iam.apps }}
    {{-     if $app_values.enable }}
    - backendRefs:
        - name: {{ print $fullName "-" ($app_values.dedicatedDeployment.suffix | default $app) }}
          port: 80
      matches:
        - path:
            value: {{ print "/" ($.Values.iam.apps.adminapp.path | default (print $.Values.iam.instanceName "-" $app)) }}
            type: PathPrefix
      {{- if ne $.Values.ingress.timeout "" }}
      timeouts:
        backendRequest: {{ $.Values.ingress.timeout }}
      {{- end }}
    {{-     end }}
    {{-   end }}
    {{- end }}
{{- end -}}
