{{- if eq .Values.ingress.type "ingress" -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  rules:
    - host: {{ $.Values.ingress.dns.hostname }}
      http:
        paths:
        {{- if eq .Values.iam.appDeploymentStrategy "single" }}
        - backend:
            service:
              name: {{ $fullName }}
              port:
                number: 80
          path: "/"
          pathType: Prefix
        {{- else if eq .Values.iam.appDeploymentStrategy "multi" }}
        {{-   range $app, $app_values := .Values.iam.apps }}
        {{-     if $app_values.enable }}
        - backend:
            service:
              name: {{ print $fullName "-" ($app_values.dedicatedDeployment.suffix | default $app) }}
              port:
                number: 80
          path: {{ print "/" ($.Values.iam.apps.adminapp.path | default (print $.Values.iam.instanceName "-" $app)) }}
          pathType: Prefix
        {{-     end }}
        {{-   end }}
        {{- end }}
  {{- if ne $.Values.ingress.tls.secretName "" }}
  tls:
  - hosts:
    - {{ $.Values.ingress.dns.hostname }}
    {{- with $.Values.ingress.tls.secretName }}
    secretName: {{ . }}
    {{- end -}}
  {{- end }}
{{- end -}}
