{{- if has .Values.ingress.type (list "gatewayAPI" "httproute" "microgateway") -}}
{{-   $fullName := include "airlock-iam.fullname" . -}}
{{-   $app := "" -}}
{{-   if has .Values.iam.defaultApp (list "loginapp" "adminapp") -}}
{{-     $app = .Values.iam.defaultApp -}}
{{-   end -}}
{{-   if ne $app "" -}}
{{-     $app_values := get $.Values.iam.apps $app -}}
{{-     $path := include "airlock-iam.modulePath" (dict "app" $app "app_values" $app_values "instanceName" $.Values.iam.instanceName) -}}
{{-     $moduleType := include "airlock-iam.mapAppName" $app -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}-redirect
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $moduleType }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
  {{- if contains "/" $.Values.ingress.gatewayAPI.gateway }}
    - name: {{ regexSplit "/" $.Values.ingress.gatewayAPI.gateway -1 | last }}
      namespace: {{ regexSplit "/" $.Values.ingress.gatewayAPI.gateway -1 | first }}
  {{- else }}
    - name: {{ $.Values.ingress.gatewayAPI.gateway }}
    {{- if ne $.Values.ingress.gatewayAPI.namespace "" }}
    - namespace: {{ $.Values.ingress.gatewayAPI.namespace }}
    {{- end }}
  {{- end }}
    {{- if $.Values.ingress.gatewayAPI.sectionName }}
      sectionName: {{ $.Values.ingress.gatewayAPI.sectionName }}
    {{- end }}
    {{- if ne (int $.Values.ingress.gatewayAPI.port) 0 }}
      port: {{ $.Values.ingress.gatewayAPI.port }}
    {{- end }}
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ $.Values.ingress.dns.hostname }}
  rules:
    - backendRefs:
        {{- if eq $.Values.iam.appDeploymentStrategy "single" }}
        - name: {{ $fullName }}
          port:  {{ ternary 443 80 $.Values.iam.combined.backendTLS.enable }}
        {{- else if eq $.Values.iam.appDeploymentStrategy "multi" }}
        - name: {{ print $fullName "-" ($app_values.dedicatedDeployment.suffix | default (include "airlock-iam.mapAppName" $app)) }}
          port: {{ ternary 443 80 $app_values.dedicatedDeployment.backendTLS.enable }}
        {{- end }}
          weight: 1
          group: ''
          kind: Service
      matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: {{ $path }}
            statusCode: 302
{{-   end -}}
{{- end -}}
