{{- $fullName := include "airlock-iam.fullname" . -}}
{{- $deploymentType := include "airlock-iam.deploymentType" . -}}
{{- if eq $deploymentType "external" -}}
{{-   $cnt := 0 -}}
{{-   range $key, $val := $.Values.database.external.credentials -}}
{{-     if and (eq $val.existingSecret "") (ne $val.value "") -}}
{{-       $cnt = add $cnt 1 -}}
{{-     end -}}
{{-   end -}}
{{-   range $key, $val := $.Values.database.initialisation.administrator.credentials -}}
{{-     if and (eq $val.existingSecret "") (ne $val.value "") -}}
{{-       $cnt = add $cnt 1 -}}
{{-     end -}}
{{-   end -}}
{{-   if gt $cnt 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := $.Values.database.external.credentials }}
  {{-   if and (eq $val.existingSecret "") (ne $val.value "") }}
  {{      $val.key }}: {{ $val.value | quote }}
  {{-   end }}
  {{- end }}
  {{- range $key, $val := $.Values.database.initialisation.administrator.credentials }}
  {{-   if and (eq $val.existingSecret "") (ne $val.value "") }}
  {{      $val.key }}: {{ $val.value | quote }}
  {{-   end }}
  {{- end }}
{{-   end }}
{{- end }}

