{{- $fullName := include "airlock-iam.fullname" . -}}
{{- $deploymentType := include "airlock-iam.deploymentType" . -}}
{{- $cnt := 0 -}}
{{- range $key, $val := $.Values.database.credentials -}}
{{-   if and (eq $val.existingSecret "") (ne $val.value "") -}}
{{-     $cnt = add $cnt 1 -}}
{{-   end -}}
{{- end -}}
{{- range $key, $val := $.Values.database.initialisation.administrator.credentials -}}
{{-   if and (eq $val.existingSecret "") (ne $val.value "") -}}
{{-     $cnt = add $cnt 1 -}}
{{-   end -}}
{{- end -}}
{{- if .Values.database.embedded.postgresql }}
{{-   $cnt = add $cnt 1 -}}
{{- end -}}
{{- if ne $.Values.iam.config.source.url "" -}}
{{-   range $key, $val := $.Values.iam.config.source.git.credentials -}}
{{-     if and (eq $val.existingSecret "") (ne $val.value "") -}}
{{-       $cnt = add $cnt 1 -}}
{{-     end -}}
{{-   end -}}
{{- end -}}
{{- if gt $cnt 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
    {{- if .Values.database.embedded.mariadb }}
    k8s.mariadb.com/watch: ""
    {{- end }}
  annotations:
    {{- include "airlock-iam.annotations" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := $.Values.database.credentials }}
  {{-   if and (eq $val.existingSecret "") (ne $val.value "") }}
  {{-     if and $.Values.database.embedded.postgresql (eq $key "user") }}
  username: {{ $val.value | quote }}
  {{-     else if and $.Values.database.embedded.postgresql (eq $key "password") }}
  password: {{ $val.value | quote }}
  {{-     else }}
  {{      $val.key }}: {{ $val.value | quote }}
  {{-     end }}
  {{-   end }}
  {{- end }}
  {{- range $key, $val := $.Values.database.initialisation.administrator.credentials }}
  {{-   if and (eq $val.existingSecret "") (ne $val.value "") }}
  {{      $val.key }}: {{ $val.value | quote }}
  {{-   end }}
  {{- end }}
  {{- if ne $.Values.iam.config.source.url "" -}}
  {{-   range $key, $val := $.Values.iam.config.source.git.credentials }}
  {{-     if and (eq $val.existingSecret "") (ne $val.value "") }}
  {{        $val.key }}: {{ $val.value | quote }}
  {{-     end }}
  {{-   end }}
  {{- end }}
{{- end }}

