{{- $fullName := include "airlock-iam.fullname" . -}}
{{- if eq .Values.iam.appDeploymentStrategy "single" -}}
{{-   $_ := set . "IAM" (dict "fullName" $fullName
                              "suffix" ""
                              "module" ""
                              "service" .Values.service) -}}
---
{{-   tpl ($.Files.Get "include/_service.yaml") . -}}

{{- else if eq .Values.iam.appDeploymentStrategy "multi" -}}
{{-   range $app, $app_values := .Values.iam.apps -}}
{{-     if $app_values.enable -}}
{{-       $_ := set $ "IAM" (dict "fullName" $fullName
                                  "suffix" ($app_values.dedicatedDeployment.suffix | default (include "airlock-iam.mapAppName" $app))
                                  "module" (include "airlock-iam.mapAppName" $app)
                                  "service" $.Values.service) -}}
---
{{-       tpl ($.Files.Get "include/_service.yaml") $ -}}
{{-     end -}}
{{-   end -}}
{{- end -}}
