{{- $fullName := include "airlock-iam.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    {{- include "airlock-iam.labels" $ | nindent 4 }}
