{{- $fullName := include "airlock-iam.fullname" . -}}
{{- $the_name := $fullName -}}
{{- $hasSandbox := include "airlock-iam.hasSandbox" . -}}
{{- if eq $hasSandbox "true" -}}
{{-   range $app, $app_values := .Values.iam.apps -}}
{{-     if and (and $app_values.enable $app_values.sandbox.enable) (gt (int $app_values.sandbox.replicas) 1) -}}
{{-       $suffix := ternary $app_values.sandbox.suffix $app (ne $app_values.sandbox.suffix "") -}}
{{-       $the_name = print $fullName "-" $suffix -}}
{{-       $instanceProp := deepCopy $.Values.iam.instanceProperties.default -}}
{{-       $nameProp := $app_values.sandbox.propertiesName | default "default" -}}
{{-       if hasKey $.Values.iam.instanceProperties $nameProp -}}
{{-         $instanceProp = mergeOverwrite $instanceProp (get $.Values.iam.instanceProperties $nameProp) -}}
{{-       end -}}
{{-       $_ := set $ "IAM_the_name" $the_name -}}
{{-       $_ := set $ "IAM_suffix" $suffix -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $the_name }}
  labels:
    {{- include "airlock-iam.labels" $ | nindent 4 }}
spec:
  replicas: {{ $app_values.sandbox.replicas }}
  revisionHistoryLimit: {{ $.Values.deployment.revisionHistoryLimit }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "airlock-iam.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airlock-iam.labels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ $fullName }}
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      {{- if $.Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ $.Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: {{ $the_name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ quote $.Values.image.pullPolicy }}
          args: ["run", "-i", {{ quote $.Values.iam.instanceName }}]
          env:
            {{- if $.Values.iam.environmentId }}
            - name: IAM_ENVIRONMENT_ID
              value: {{ $.Values.iam.environmentId }}
            {{- end }}
            - name: IAM_CONFIG_FORMAT
              value: {{ ternary "xml" "yaml" (eq (lower $.Values.iam.configFormat) "xml") }}
            {{- if $.Values.iam.apps.adminapp.path }}
            - name: IAM_ADMINAPP_URL_PATH
              value: {{ $.Values.iam.apps.adminapp.path }}
            {{- end }}
            {{- if $.Values.iam.apps.loginapp.path }}
            - name: IAM_LOGINAPP_URL_PATH
              value: {{ $.Values.iam.apps.loginapp.path }}
            {{- end }}
            {{- if $.Values.iam.apps.transactionApproval.path }}
            - name: IAM_TRANSACTION_APPROVAL_URL_PATH
              value: {{ $.Values.iam.apps.transactionApproval.path }}
            {{- end }}
            {{- if $.Values.iam.apps.serviceContainer.path }}
            - name: IAM_SERVICE_CONTAINER_URL_PATH
              value: {{ $.Values.iam.apps.serviceContainer.path }}
            {{- end }}
            {{- if $.Values.iam.apps.apiPolicyService.path }}
            - name: IAM_API_POLICY_SERVICE_URL_PATH
              value: {{ $.Values.iam.apps.apiPolicyService.path }}
            {{- end }}
            - name: IAM_MODULES
              value: {{ include "airlock-iam.mapAppName" $app }}
            - name: IAM_WEB_SERVER_CONNECTORS
              value: "http,https"
            - name: IAM_WEB_SERVER_HTTP_PORT
              value: "8080"
            - name: IAM_WEB_SERVER_HTTPS_PORT
              value: "8443"
            {{- if eq $instanceProp.logging.level "" }}
            - name: IAM_LOG_LEVEL
              value: INFO
            {{- else if ne $instanceProp.logging.level "" }}
            - name: IAM_LOG_LEVEL
              value: {{ $instanceProp.logging.level }}
            {{- end }}
            {{- if $instanceProp.logging.local.enable }}
            {{-   if $instanceProp.logging.local.structured }}
            - name: IAM_LOG_STRUCTURED_FILE_ENABLED
              value: "true"
            - name: IAM_LOG_MAIN_ENABLED
              value: "false"
            {{-   else }}
            - name: IAM_LOG_STRUCTURED_FILE_ENABLED
              value: "false"
            - name: IAM_LOG_MAIN_ENABLED
              value: "true"
            {{-   end }}
            {{- end }}
            {{- if $instanceProp.logging.elasticsearchUrl }}
            - name: IAM_LOG_ELASTICSEARCH_URL
              value: {{ $instanceProp.logging.elasticsearchUrl }}
            {{- end }}
            {{- if $instanceProp.logging.webserver }}
            - name: IAM_WEB_SERVER_ACCESS_LOG_FILE_ENABLED
              value: "true"
            {{- end }}
            {{- if $instanceProp.metrics }}
            - name: IAM_METRICS_PORT
              value: {{ quote $instanceProp.metrics }}
            {{- end }}
            - name: IAM_HEALTH_PORT
              value: "8081"
            {{- range $name, $value := mergeOverwrite $.Values.env $instanceProp.env $app_values.sandbox.env }}
            - name: {{ quote $name }}
              value: {{ quote $value }}
            {{- end }}
            - name: TZ
              value: {{ $.Values.global.timezone }}
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: health
          {{- if $app_values.sandbox.healthChecks.liveness.enable }}
          livenessProbe:
            periodSeconds: {{ $app_values.sandbox.healthChecks.liveness.period }}
            timeoutSeconds: {{ $app_values.sandbox.healthChecks.liveness.timeout }}
            failureThreshold: {{ $app_values.sandbox.healthChecks.liveness.failures }}
            initialDelaySeconds: {{ $app_values.sandbox.healthChecks.liveness.initialDelay }}
            httpGet:
              path: /health/ready
              port: health
          {{- end }}
          {{- if $app_values.sandbox.healthChecks.readiness.enable }}
          readinessProbe:
            periodSeconds: {{ $app_values.sandbox.healthChecks.readiness.period }}
            timeoutSeconds: {{ $app_values.sandbox.healthChecks.readiness.timeout }}
            failureThreshold: {{ $app_values.sandbox.healthChecks.readiness.failures }}
            initialDelaySeconds: {{ $app_values.sandbox.healthChecks.readiness.initialDelay }}
            httpGet:
              path: /health/live
              port: health
          {{- end }}
          {{- if $app_values.sandbox.healthChecks.startup.enable }}
          startupProbe:
            periodSeconds: {{ $app_values.sandbox.healthChecks.startup.period }}
            timeoutSeconds: {{ $app_values.sandbox.healthChecks.startup.timeout }}
            failureThreshold: {{ $app_values.sandbox.healthChecks.startup.failures }}
            initialDelaySeconds: {{ $app_values.sandbox.healthChecks.startup.initialDelay }}
            httpGet:
              path: /health/ready
              port: health
          {{- end }}
          resources:
            {{- if or (ne $app_values.sandbox.resources.requests.cpu "") (ne $app_values.sandbox.resources.requests.ram "") }}
            requests:
              {{- if or (ne $app_values.sandbox.resources.requests.cpu "") }}
              cpu: {{ $app_values.sandbox.resources.requests.cpu }}
              {{- end }}
              {{- if or (ne $app_values.sandbox.resources.requests.ram "") }}
              memory: {{ $app_values.sandbox.resources.requests.ram }}
              {{- end }}
            {{- end }}
            {{- if or (ne $app_values.sandbox.resources.limits.cpu "") (ne $app_values.sandbox.resources.limits.ram "") }}
            limits:
              {{- if or (ne $app_values.sandbox.resources.limits.cpu "") }}
              cpu: {{ $app_values.sandbox.resources.limits.cpu }}
              {{- end }}
              {{- if or (ne $app_values.sandbox.resources.limits.ram "") }}
              memory: {{ $app_values.sandbox.resources.limits.ram }}
              {{- end }}
            {{- end }}
    {{- if $.Values.resourceOptions }}
          resources:
    {{ toYaml $.Values.resourceOptions | indent 8 }}
    {{- end }}
          volumeMounts:
            {{- if or $app_values.sandbox.persistence.config.enable $.Values.persistence.config.enable }}
            - mountPath: /home/airlock/iam/instances
              name: config
            {{- end }}
            - mountPath: {{ print "/home/airlock/iam/instances/" $.Values.iam.instanceName "/logs" }}
              name: {{ print $fullName "-" $app "-" (ternary $app_values.sandbox.persistence.logs.claim "logs" (ne $app_values.sandbox.persistence.logs.claim "")) }}
            - mountPath: /home/airlock/iam/license.txt
              name: license
              subPath: license.txt
            - mountPath: /home/airlock/work
              name: work
      restartPolicy: {{ quote $.Values.restartPolicy }}
      volumes:
        {{- if $app_values.sandbox.persistence.config.enable }}
        - name: config
          {{- if eq $app_values.sandbox.persistence.config.type "request" }}
          persistentVolumeClaim:
            claimName: {{ print $fullName "-" $app "-" (ternary $app_values.sandbox.persistence.config.claim "config" (ne $app_values.sandbox.persistence.config.claim "")) }}
          {{- else if eq $app_values.sandbox.persistence.config.type "existing" }}
          persistentVolumeClaim:
            claimName: {{ $app_values.sandbox.persistence.config.claim }}
          {{- else if eq $app_values.sandbox.persistence.config.type "remote" }}
          {{ $app_values.sandbox.persistence.config.remote.type }}:
            server: {{ $app_values.sandbox.persistence.config.remote.server }}
            path: {{ $app_values.sandbox.persistence.config.remote.path }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- else if $.Values.persistence.config.enable }}
        - name: config
          {{- if eq $.Values.persistence.config.type "request" }}
          persistentVolumeClaim:
            claimName: {{ print $fullName "-" (ternary $.Values.persistence.config.claim "config" (ne $.Values.persistence.config.claim "" )) }}
          {{- else if eq $.Values.persistence.config.type "existing" }}
          persistentVolumeClaim:
            claimName: {{ $.Values.persistence.config.claim }}
          {{- else if eq $.Values.persistence.config.type "remote" }}
          {{ $.Values.persistence.config.remote.type }}:
            server: {{ $.Values.persistence.config.remote.server }}
            path: {{ $.Values.persistence.config.remote.path }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - name: license
          {{- if has (lower $.Values.iam.license.type) (list "cm" "configmap") }}
          configMap:
            name: {{ $.Values.iam.license.name }}
          {{- else }}
          secret:
            secretName: {{ $.Values.iam.license.name }}
          {{- end }}
        - name: work
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: {{ print $fullName "-" $app "-" (ternary $app_values.sandbox.persistence.logs.claim "logs" (ne $app_values.sandbox.persistence.logs.claim "")) }}
      spec:
        storageClassName: {{ ternary $app_values.sandbox.persistence.logs.storageClass $.Values.persistence.logs.storageClass (ne $app_values.sandbox.persistence.logs.storageClass "") }}
        accessModes:
          - {{ ternary $app_values.sandbox.persistence.logs.accessMode (ternary $.Values.persistence.logs.accessMode "ReadWriteOnce" (ne $.Values.persistence.logs.accessMode "")) (ne $app_values.sandbox.persistence.logs.accessMode "") }}
        resources:
          requests:
            storage: {{ ternary $app_values.sandbox.persistence.logs.size $.Values.persistence.logs.size (ne $app_values.sandbox.persistence.logs.size "") }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ ternary $app_values.sandbox.persistence.logs.replicaRetentionPolicy $.Values.persistence.logs.replicaRetentionPolicy (ne $app_values.sandbox.persistence.logs.replicaRetentionPolicy "") }}
    whenScaled: {{ ternary $app_values.sandbox.persistence.logs.replicaRetentionPolicy $.Values.persistence.logs.replicaRetentionPolicy (ne $app_values.sandbox.persistence.logs.replicaRetentionPolicy "") }}
{{-     end -}}
{{-   end -}}
{{- end -}}
