#! /bin/bash

if [[ -r "${INIT_ENV_PATH:-.}"/env.init ]]; then
    echo "Loading variables from '${INIT_ENV_PATH:-.}/env.init'"
    source "${INIT_ENV_PATH:-.}"/env.init
fi

function die ()
{
    echo $@
    # do not exit to indicate problem
    while true
    do
        sleep 10
    done
}

# sanity checks
# - not checking INSTANCE_DIR, INIT_DB_MIRROR
for f in INIT_INSTANCE INIT_INSTANCE_CREATE
do
  [[ -z "${!f}" ]] && die "${f} not set"
done
echo "Variables checked"

instance_dir="${INSTANCE_DIR:-/home/airlock/iam/instances}/${INIT_INSTANCE}"

# ###########
# Create instance
# ###########

if [[ "${INIT_INSTANCE_CREATE}" == "true" ]]; then
    if [[ -d "${instance_dir}" ]]; then
        echo "Instance ${INIT_INSTANCE} exists - doing nothing"
    else
        /opt/airlock-iam/bin/iam init -i "${INIT_INSTANCE}" || die "Failed to create instance '${INIT_INSTANCE}'"
        if [[ -d "${instance_dir}" ]]; then
            echo "Instance ${INIT_INSTANCE} created"
        else
            die "Failed to create instance '${INIT_INSTANCE}'"
        fi
        if [[ "${INIT_CONFIG_FORMAT}" == "yaml" ]]; then
            /opt/airlock-iam/bin/iam config convert -i "${INIT_INSTANCE}" || die "Failed to convert instance '${INIT_INSTANCE}' to YAML config format"
            rm -f "${instance_dir}"/medusa-configuration.xml
        fi
    fi
fi

